
window.APP_CONFIG = {
  APP_NAME: "Label Generator",
  GOOGLE_CLIENT_ID: "REMPLACE_PAR_TON_CLIENT_ID_OAUTH",
  DEFAULT_DRIVE_FOLDER_ID: "",
  MAX_ROWS: 300,
  DEFAULT_DPI: 200,
  DEFAULT_SHARE_PUBLICLY: false
};
